### ISSUE TITLE
spaces 

### ISSUE THREAD

**Issue by minhnhatspk** [NickNaso/ghostscript4js#39]
As discussion https://stackoverflow.com/questions/42578061/ghostscript-and-spaces-in-filenames
I see that on the version 3.0.0 you already resolved this problem, but I'm using electron and after updating to v3.0.0 I got some problem.
so how can I fix this error without updating version to 3.0.0? 
I'm using v2.0.7.

**Comment by NickNaso** [comment]
Hi @minhnhatspk,
the version 3.0.0 uses N-API and I can say that with some version of electron we there are some issues with N-API. I solved the space problem in version 3.0.0 because I added a new way to set parameter to pass at execute function like an array. 
I'm interested on knowing the error that you get when use the version 3.0.0 with electron. Could you post it here?

**Comment by minhnhatspk** [comment]
Here is the error I got
![image](https://user-images.githubusercontent.com/21996261/48342791-36e78380-e6a3-11e8-8d69-c246540b8887.png)
ghostscript4js v3.0.0
electron v1.8.8
It also occurs the same error when I add --napi-modules to my command.

**Comment by NickNaso** [comment]
Do you know which version of Node.js embed the version of electron you are using?

**Comment by minhnhatspk** [comment]
> Do you know which version of Node.js embed the version of electron you are using?

I'm using Node.js version 8.12.0
